name: Nightly build MacOS Intel

on: [push]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: install_dependencies
      run: |
        brew reinstall cmake pkg-config libpng freetype zstd sdl2 fluidsynth subversion

    - name: build
      run: |
        svn checkout svn://servers.simutrans.org/simutrans/trunk . #-r 10421
        svn patch tmp.diff
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DOPTION_BUNDLE_LIBRARIES=ON -DSIMUTRANS_STEAM_BUILT=ON #-DSIMUTRANS_USE_REVISION=10421
        cmake --build build -j$(nproc) --target install

    - name: distribute
      run: |
        cd build
        mkdir 434524
        mv simutrans/simutrans.app 434524/
        cd 434524
        zip -r macos-434524.zip simutrans.app

    - name: Update macos depot
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/434524/macos-434524.zip
        asset_name: macos-434524.zip
        tag: Nightly
        overwrite: true
