# This workflow sets up and runs MSBuild and VSTest
# to build and test a Visual Studio solution.

name: Nightly Built Windows 32

on: [push]

jobs:
  build:
   runs-on: windows-latest
   steps:
    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Checkout code
      uses: actions/checkout@v4
      id: checkout_code

    - name: Make NSIS
      shell: pwsh
      run: |
        svn checkout svn://servers.simutrans.org/simutrans/trunk . #-r 10421
        ./.github/prepare-nsis.ps1

    - name: Run MSBuild
      shell: pwsh
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        rm vcpkg.json
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg --triplet x86-windows install zlib bzip2 libpng zstd sdl2 freetype miniupnpc
        cd ..
        cmake.exe -S . -B build -G "Visual Studio 17 2022" -A Win32 -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="x86-windows"
        cmake.exe --build build --target install --config Release

    - name: Build zipfile
      shell: pwsh
      run: |
        cd build
        mkdir 434634
        move-item "simutrans/simutrans.exe" "434634/simutrans.exe"
        cd 434634
        #move-item "src\Windows\nsis\download-paksets.exe" "simutrans/download-pakset.exe"
        Compress-Archive -Path . -DestinationPath "windows32-434634.zip"

    - name: Update windows 32 depot
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/434634/windows64-434634.zip
        asset_name: windows64-434634.zip
        tag: Nightly
        overwrite: true
